### ISSUE TITLE
Username is not saved

### ISSUE THREAD

**Issue by nekto198** [joshp23/YOURLS-AuthMgrPlus#42] opened 2021-09-17 10:14 UTC
I have installed this plugin but user name is not saved in the database. I tried any roles, it does not work for me... I have latest version. What am i doing wrong?

**Comment by DerFreistaat** [comment] 2021-09-17 11:10
Duplicate of #35

temporary solution:
https://github.com/joshp23/YOURLS-AuthMgrPlus/issues/35
worked fine for me!

**Comment by nekto198** [comment] 2021-09-17 11:36
I saw and tried it and it does not work. Try it yourself

**Comment by nekto198** [comment] 2021-09-17 11:38
May I need a special php configuration? Now I have v. 7.3

**Comment by DerFreistaat** [comment] 2021-09-17 14:37
i'm running 8.0.10 - works fine for us

**Comment by joshp23** [comment] 2021-12-28 22:34
fixed with e3cb3401c1d1c57f37d4b36465a4a84dc0707e4e

**Closed by joshp23** 2021-12-28 22:34 UTC
