### ISSUE TITLE
User name of users is not saved in the database and all links are visible to everybody

### ISSUE THREAD

**Issue by outlander65** [joshp23/YOURLS-AuthMgrPlus#40] opened 2021-07-19 06:42 UTC
Hello,
This plugin is what I was looking for, but unfortunately it's broken at this moment. The problem is that user name of users is not saved in the database and all links are visible to everybody. 
Can we expect an update for that?
Thank you in advance.

**Comment by DerFreistaat** [comment] 2021-07-22 16:39
Duplicate of #35

temporary solution: 
[https://github.com/joshp23/YOURLS-AuthMgrPlus/issues/35#issuecomment-872419767](url)
worked fine for me!

**Comment by joshp23** [comment] 2021-12-28 22:34
should be fixed with e3cb3401c1d1c57f37d4b36465a4a84dc0707e4e

**Closed by joshp23** 2021-12-28 22:34 UTC
